import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen w-screen overflow-x-hidden`}
      >
        <main className="h-[1px] min-h-[calc(100vh-88px)] w-full "></main>
        {children}
      </body>
    </html>
  )
}
